//
// Generated file, do not edit! Created by opp_msgc 4.3 from msg/CRL_Piece.msg.
//

#ifndef _CRL_PIECE_M_H_
#define _CRL_PIECE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>msg/CRL_Piece.msg</tt> by opp_msgc.
 * <pre>
 * packet CRL_Piece
 * {
 *     int CRLversion;
 *     int Timestamp;
 *     int SeqNo;
 *     int CAid;
 *     int pad;
 *     
 *     string payload;
 *   
 * }
 * </pre>
 */
class CRL_Piece : public ::cPacket
{
  protected:
    int CRLversion_var;
    int Timestamp_var;
    int SeqNo_var;
    int CAid_var;
    int pad_var;
    opp_string payload_var;

  private:
    void copy(const CRL_Piece& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CRL_Piece&);

  public:
    CRL_Piece(const char *name=NULL, int kind=0);
    CRL_Piece(const CRL_Piece& other);
    virtual ~CRL_Piece();
    CRL_Piece& operator=(const CRL_Piece& other);
    virtual CRL_Piece *dup() const {return new CRL_Piece(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getCRLversion() const;
    virtual void setCRLversion(int CRLversion);
    virtual int getTimestamp() const;
    virtual void setTimestamp(int Timestamp);
    virtual int getSeqNo() const;
    virtual void setSeqNo(int SeqNo);
    virtual int getCAid() const;
    virtual void setCAid(int CAid);
    virtual int getPad() const;
    virtual void setPad(int pad);
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doPacking(cCommBuffer *b, CRL_Piece& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CRL_Piece& obj) {obj.parsimUnpack(b);}


#endif // _CRL_PIECE_M_H_
